
sequenceDiagram
title Extremely wide sequence diagram FROM FILE
actor Configuration
actor Stage1
actor Stage2
actor Stage3
actor Stage4
actor Stage5
actor Stage6
actor Stage7
actor Stage8
actor Stage9

Configuration->>Stage1: Configure the system
Stage1->>Stage2: First stage
Stage2->>Stage3: Second stage
Stage3->>Stage4: Third stage
Stage4->>Stage5: Fourth stage
Stage5->>Stage6: Fifth stage
Stage6->>Stage7: Sixth stage
Stage7->>Stage8: Seventh stage
Stage8->>Stage9: Eighth stage

Stage9->>Stage8: First reply
Stage8->>Stage7: Second reply
Stage7->>Stage6: Third reply
Stage6->>Stage5: Fourth reply
Stage5->>Stage4: Fifth reply
Stage4->>Stage3: Sixth reply
Stage3->>Stage2: Seventh reply
Stage2->>Stage1: Eighth reply